# Generated by Django 4.0.4 on 2022-06-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_fname', models.CharField(max_length=100)),
                ('User_lname', models.CharField(max_length=100)),
                ('User_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
