# Generated by Django 4.0.4 on 2022-06-02 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(max_length=1000000)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
            ],
        ),
    ]
