# Generated by Django 4.0.4 on 2022-06-02 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
