# Generated by Django 4.0.4 on 2022-06-01 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='User',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
