# Generated by Django 4.0.4 on 2022-06-02 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_profile_user_delete_customer_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='post_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='post_title',
            field=models.CharField(default=' ', max_length=1000),
        ),
    ]
