# Generated by Django 4.0.4 on 2022-06-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_created_at_post_date_posted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ourcustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=20)),
                ('user_lname', models.CharField(max_length=20)),
                ('user_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
