# Generated by Django 4.0.4 on 2022-06-02 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_ourcustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourcustomer',
            name='username',
            field=models.CharField(default='savvy', max_length=50),
        ),
    ]
