# Generated by Django 4.0.4 on 2022-06-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_ourcustomer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourcustomer',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
