# Generated by Django 4.0.4 on 2022-06-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_address_bio_doctor_people_product_remove_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='people',
            name='lname',
        ),
        migrations.AddField(
            model_name='people',
            name='full_name',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AlterField(
            model_name='people',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
